//LOGIN ACTIONS



//AUTH ACTIONS



//REGISTER ACTIONS



//EVENT ACTIONS
export const CLEANUP_EVENT = 'CLEANUP_EVENT';
export const CHANGE_INTENSITY = 'CHANGE_INTENSITY';
export const CHANGE_EVENT_TYPE = 'CHANGE_EVENT_TYPE';
export const CHANGE_DURATION_TYPE = 'CHANGE_DURATION_TYPE';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILURE = 'POST_EVENT_FAILURE';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

//FRECKLE ACTIONS
export const ADD_FRECKLE_COUNT = 'ADD_FRECKLE_COUNT';
export const CLEANUP_FRECKLE = 'CLEANUP_FRECKLE';

//MARKER DIMENSIONS ACTIONS
export const CHANGE_MARKER_DIMENSIONS = 'CHANGE_MARKER_DIMENSIONS';
export const CLEANUP_MARKER_DIMENSIONS = 'CLEANUP_MARKER_DIMENSIONS';

//MARKER ACTIONS
export const ADD_MARKER = 'ADD_MARKER';
export const CLEANUP_MARKER = 'CLEANUP_MARKER';
export const CHANGE_MARKER_MENU = 'CHANGE_MARKER_MENU';
export const CHANGE_MARKER_LOCATION = 'CHANGE_MARKER_LOCATION';
export const CHANGE_MARKER_TYPE = 'CHANGE_MARKER_TYPE';
export const POST_MARKER_SUCCESS = 'POST_MARKER_SUCCESS';
export const POST_MARKER_FAILURE = 'POST_MARKER_FAILURE';
export const GET_MARKER_SUCCESS = 'GET_MARKER_SUCCESS';
export const GET_MARKER_FAILURE = 'GET_MARKER_FAILURE';

//BODY LOCATION ACTIONS
export const CHANGE_BODY_LOCATION = 'CHANGE_BODY_LOCATION';
export const CLEANUP_LOCATION = 'CLEANUP_LOCATION';
export const ADD_BODY_LOCATION = 'ADD_BODY_LOCATION';

//LOG HISTORY ACTIONS
export const CLEANUP_LOG_HISTORY = 'CLEANUP_LOG_HISTORY';

// PHOTO UPLOAD TESTING
export const NEW_IMAGE_TO_STORE = 'NEW_IMAGE_TO_STORE';
export const CLEAR_IMAGE_STORE = 'CLEAR_IMAGE_STORE';
